version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_wordpress_database
      MYSQL_USER: your_wordpress_user
      MYSQL_PASSWORD: your_wordpress_password

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_wordpress_user
      WORDPRESS_DB_PASSWORD: your_wordpress_password
      WORDPRESS_DB_NAME: your_wordpress_database

volumes:
  db_data:
